### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mattattui** [renasboy/php-color-difference#1]
I'd love to know if I can use this freely. If you don't much care, would you mind adding a license (e.g. MIT/BSD)?

Also happy to contribute a `composer.json` & PSR-4 update, although namespacing it will break compatibility. What do you think? I can fork it if it's too much trouble (provided you're okay with it and license it accordingly)

**Comment by renasboy** [comment]
Hey, great to see someone interested on it, feel free to fork it and change as you would like, I have not being using it for a while and NO, I have no problems with lincese, keep in mind I used some algos I found onlne in order to create this php version.
